#ifndef CONFIG_H
#define CONFIG_H

#define PLAY_PAUSE_BUTTON_PIN 2
#define RESET_BUTTON_PIN 3
#define PLUS_BUTTON_PIN 4
#define LESS_BUTTON_PIN 5

#define POLLING_PERIOD 150 //Time in milliseconds

#define DEFAULT_REGULAR_GAME_TIME_MINUTES 1
#define DEFAULT_REGULAR_GAME_TIME_SECONDS 0
#define DEFAULT_ADDITION_GAME_MINUTES 1
#define DEFAULT_ADDITION_GAME_SECONDS 0

#endif